### ISSUE TITLE
Question on tutorial

### ISSUE THREAD

**Issue by WonwoongCho** [xqding/RealNVP#2]
Hi, I am able to study easily RealNVP thanks to your well constructed tutorial. Thank you.
By the way,
I have a question on the necessity of self.scale in def _compute_scale.
Why is it necessary, and what role exactly it plays in?

Thank you for reading my question.

**Comment by xqding** [comment]
I am glad that it is helpful for you!
 You can still learn the RealNVP model without the parameter self.scale, but I found that including it can make the model more flexible and easier to learn on more complex distributions. Because we are using torch.relu function at the [end](https://github.com/xqding/RealNVP/blob/72bf0424bf7c4e0f6a9c23bf98c723de068a2a7c/script/RealNVP_2D.py#L36) of _compute_scale, without self.scale, the scale function will already return a positive number, which means the exp(scale) will be always larger than 1, expanding the corresponding dimensions. Including self.scale can relax this limitation. Of course, you can also change the relu to other activation functions such as sigmoid so that it can return both positive and negative numbers. In summary, it is not strictly necessary, but it helps improve the model's flexibility in this case.

**Comment by WonwoongCho** [comment]
Got your point. Thank you :)
